### ISSUE TITLE
Installation link returns 404 on josemiguel.org/styled-bootstrap/

### ISSUE THREAD

**Issue by apaatsio** [xDae/styled-bootstrap#103]
The "Installation" link button on http://josemiguel.org/styled-bootstrap/ takes to http://josemiguel.org/styled-bootstrap/docs/doc1.html which returns 404.

**Comment by JohnTheo13** [comment]
@apaatsio 
A lot of links are not working since it's under construction and the project is not ready.

**Comment by xDae** [comment]
The documentation is still on going, soon will be ready 🚀
