### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by juanitoddd** [xDae/styled-bootstrap#99]
Hello, first of all, I want to thank you for open sourcing this awesome idea.

I am looking forward to contribute and extend this repo, but I cant get the storybook script to run properly:

after "npm start" I get:
> Error: Can't resolve styled-bootstrap/utils

Am I missing something obvious ? I already install all dependencies. and "lerna ls" throws me:

> styled-bootstrap/alert      v0.1.6-6 
> styled-bootstrap/button     v0.1.6-6 
> styled-bootstrap/close-icon v0.1.6-6 
> styled-bootstrap/utils      v0.1.6-3

**Comment by xDae** [comment]
Hi @juanitoddd, I didn't notice about this issue before, just to let you know, I'm rebuilding all the components.

At the beginning I wanted to build the components separately, buy I got some errors and had some problems with lerna, now Im working in a new version, with other approach

Soon we will have a new/better version of this library

**Comment by adamchenwei** [comment]
is this still the case?

**Comment by xDae** [comment]
@adamchenwei this problem could be considered as deprecated
